/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FormRouteRouteImport } from './routes/_form/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormUploadRouteImport } from './routes/_form/upload'
import { Route as FormText_infoRouteImport } from './routes/_form/text_info'
import { Route as FormSelect_textRouteImport } from './routes/_form/select_text'
import { Route as FormSelect_authorRouteImport } from './routes/_form/select_author'
import { Route as FormAuthor_infoRouteImport } from './routes/_form/author_info'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRouteRoute = FormRouteRouteImport.update({
  id: '/_form',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormUploadRoute = FormUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => FormRouteRoute,
} as any)
const FormText_infoRoute = FormText_infoRouteImport.update({
  id: '/text_info',
  path: '/text_info',
  getParentRoute: () => FormRouteRoute,
} as any)
const FormSelect_textRoute = FormSelect_textRouteImport.update({
  id: '/select_text',
  path: '/select_text',
  getParentRoute: () => FormRouteRoute,
} as any)
const FormSelect_authorRoute = FormSelect_authorRouteImport.update({
  id: '/select_author',
  path: '/select_author',
  getParentRoute: () => FormRouteRoute,
} as any)
const FormAuthor_infoRoute = FormAuthor_infoRouteImport.update({
  id: '/author_info',
  path: '/author_info',
  getParentRoute: () => FormRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sessions': typeof SessionsRoute
  '/author_info': typeof FormAuthor_infoRoute
  '/select_author': typeof FormSelect_authorRoute
  '/select_text': typeof FormSelect_textRoute
  '/text_info': typeof FormText_infoRoute
  '/upload': typeof FormUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sessions': typeof SessionsRoute
  '/author_info': typeof FormAuthor_infoRoute
  '/select_author': typeof FormSelect_authorRoute
  '/select_text': typeof FormSelect_textRoute
  '/text_info': typeof FormText_infoRoute
  '/upload': typeof FormUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_form': typeof FormRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sessions': typeof SessionsRoute
  '/_form/author_info': typeof FormAuthor_infoRoute
  '/_form/select_author': typeof FormSelect_authorRoute
  '/_form/select_text': typeof FormSelect_textRoute
  '/_form/text_info': typeof FormText_infoRoute
  '/_form/upload': typeof FormUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sessions'
    | '/author_info'
    | '/select_author'
    | '/select_text'
    | '/text_info'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sessions'
    | '/author_info'
    | '/select_author'
    | '/select_text'
    | '/text_info'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/_form'
    | '/login'
    | '/sessions'
    | '/_form/author_info'
    | '/_form/select_author'
    | '/_form/select_text'
    | '/_form/text_info'
    | '/_form/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormRouteRoute: typeof FormRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SessionsRoute: typeof SessionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_form': {
      id: '/_form'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof FormRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_form/upload': {
      id: '/_form/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof FormUploadRouteImport
      parentRoute: typeof FormRouteRoute
    }
    '/_form/text_info': {
      id: '/_form/text_info'
      path: '/text_info'
      fullPath: '/text_info'
      preLoaderRoute: typeof FormText_infoRouteImport
      parentRoute: typeof FormRouteRoute
    }
    '/_form/select_text': {
      id: '/_form/select_text'
      path: '/select_text'
      fullPath: '/select_text'
      preLoaderRoute: typeof FormSelect_textRouteImport
      parentRoute: typeof FormRouteRoute
    }
    '/_form/select_author': {
      id: '/_form/select_author'
      path: '/select_author'
      fullPath: '/select_author'
      preLoaderRoute: typeof FormSelect_authorRouteImport
      parentRoute: typeof FormRouteRoute
    }
    '/_form/author_info': {
      id: '/_form/author_info'
      path: '/author_info'
      fullPath: '/author_info'
      preLoaderRoute: typeof FormAuthor_infoRouteImport
      parentRoute: typeof FormRouteRoute
    }
  }
}

interface FormRouteRouteChildren {
  FormAuthor_infoRoute: typeof FormAuthor_infoRoute
  FormSelect_authorRoute: typeof FormSelect_authorRoute
  FormSelect_textRoute: typeof FormSelect_textRoute
  FormText_infoRoute: typeof FormText_infoRoute
  FormUploadRoute: typeof FormUploadRoute
}

const FormRouteRouteChildren: FormRouteRouteChildren = {
  FormAuthor_infoRoute: FormAuthor_infoRoute,
  FormSelect_authorRoute: FormSelect_authorRoute,
  FormSelect_textRoute: FormSelect_textRoute,
  FormText_infoRoute: FormText_infoRoute,
  FormUploadRoute: FormUploadRoute,
}

const FormRouteRouteWithChildren = FormRouteRoute._addFileChildren(
  FormRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormRouteRoute: FormRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SessionsRoute: SessionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
